### ISSUE TITLE
Bad project tag names

### ISSUE THREAD

**Issue by hugopl** [acoustep/fuzzy_match.cr#3]
Hi,

You tagged the releases as `0.1.0`, `0.2.0`, `v0.2.0` and `0.3.0`, seems that shard tool can only find version with the `v` prefix, this explains why I was able to use the v0.2.0 but I'm not able to upgrade to v0.3.0.

I get:
```
Failed to match versions for #<Shards::Dependency {fuzzy_match => {"github" => "acoustep/fuzzy_match.cr", "version" => "~> 0.3.0"}}>
```

Anyway.. I would suggest to remove the version tags without the `v` prefix and add them with the prefix, so shard tool can work and you avoid possible git conflicts in case you decide to create a version branch in the future.

**Comment by acoustep** [comment]
Thanks for spotting that. I've updated the tag so you should be able to install it.

**Comment by hugopl** [comment]
It's working now, thanks.
